apps/article/urls.py
#!/usr/bin/python  
# -*- coding:utf-8 -*-
from django.urls import path
app_name='article'
from . import views
urlpatterns = [

  path('', views.ArticleList, name='index'),

  path('created/',views.Article_Add,name='created'),
  path('me/',views.ArticleMe,name='me'),
  path('',views.ArticleList,name='index'),
  path('blog_img_upload/',views.blog_img_upload,name='blog_img_upload'),
  path('detail/<uuid:article_id>',views.Article_detail,name='detail'),
  path('update/<uuid:article_id>',views.ArticleUpdate,name='update'),
  path('update_image/<uuid:article_id>',views.RemoveImage,name='update_image'),
  path('delete/',views.ArticleDelete,name='delete'),
]

apps/course/urls.py
#!/usr/bin/python  
# -*- coding:utf-8 -*-  
from django.conf.urls import url
from django.urls import path, include
app_name='course'
from . import views
urlpatterns = [

  path('',views.List,name='index'),

  path('<uuid:course_id>/<str:list_id>.html/',views.Detail,name='detail'),


  path('api/<uuid:courses_id>/',views.courseViewApi,name='courseViewApi'),

]

apps/forum/urls.py
#!/usr/bin/python  
# -*- coding:utf-8 -*-  
#!/usr/bin/python
# -*- coding:utf-8 -*-
from django.conf.urls import url
from django.urls import path, include
app_name='forum'
from . import views

urlpatterns = [
  #path('',views.login_view,name='index'),
  path('',views.index,name='forum'),
  path('add/',views.add_forum,name='add'),
  path('detail/<uuid:forum_id>/',views.forum_detail,name='detail'),
  path('update/<uuid:forum_id>/',views.update_forum,name='update'),
  path('cagetory/<int:category>/',views.forum_category,name='id'),
  path('del/<uuid:id>/',views.delForum,name='del'),
  ]

apps/support/urls.py
#!/usr/bin/python  
# -*- coding:utf-8 -*-  
#!/usr/bin/python
# -*- coding:utf-8 -*-
from django.conf.urls import url
from django.urls import path, include
app_name='support'
from . import views
urlpatterns = [
  #path('',views.login_view,name='index'),
  path('',views.index,name='support'),

]

apps/user/urls.py
#!/usr/bin/python  
# -*- coding:utf-8 -*-  
#!/usr/bin/python
# -*- coding:utf-8 -*-
from django.conf.urls import url
from django.urls import path, include
app_name='user'
from . import views
from apps.forum.views import indexMe
from django.views.generic import TemplateView
urlpatterns = [
  #path('',views.login_view,name='index'),
  path('',views.Person.as_view(),name='person'),
  path('author/',views.Author.as_view(),name='author'),
  path('<uuid:article_id>/',views.PersonDetaile.as_view(),name='author_detaile'),
  path('info/<uuid:article_id>/',views.InfoOthers.as_view(),name='info'),
  path('ProfileOthers/<uuid:article_id>/',views.ProfileOthers,name='ProfileOthers'),
  path('profile/', views.Profile,name='profile'),
  path('info/', views.Info, name='info'),
  path('forum/', indexMe, name='forum'),
  path('modify/', views.Modify.as_view(), name='modify'),
  path('retrieve/', views.Retrieve.as_view(), name='retrieve '),
  path('sing_email/', views.ResetUserView.as_view(), name='sing_email'),
  path('email_update/', views.EmailView.as_view(), name='email_update'),
  path('Guan/', views.Guan, name='Guan'),
  path('retrieveEmail/', views.RetrieveEmail.as_view(), name='retrieveEmail'),
  path('message/', views.message, name='message'),
  path('bindingQQ/', views.bindingQQ, name='bindingQQ'),
]

website/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from rest_framework.documentation import include_docs_urls

from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token

from apps.article.views import ArticleCreated
from apps.course.views import CoursesList, CourseCreatedList, CourseListCreated, MeCoursesList
from apps.dynamic .views import Home
from apps.forum.views import Forum_plateView, ForumView, CommentView, Parent_CommentView, ForumListView
from apps.support.views import LinkList, EmailsList, BannerList, QQList, SeoList
from apps.user.views import test, captcha_refresh, yan, login_view, UserGetInfo, UserGetAllInfo, \
    PersonOthers, Register, active_user, get_message, UserMessages, qq, getClback, getClbackQQ, UserFollows, AppMessage, \
    UserFollowOther
from django.views.generic import TemplateView

from website import settings
from apps.article import views
from apps.user.views import logout_view, Person, PersonApi,to_login
from rest_framework import routers

router = routers.DefaultRouter()
router.register('article_list', views.ArticleListView)
router.register('me_article_list', views.MeArticleListView)
router.register('ArticleCommit', views.ArticleCommit)
router.register('follow_list', views.FollowListView)
router.register('category', views.CategoryView)
router.register('article_Comment', views.ArticleCommintView)
router.register('comment_reply', views.ArticleCommentReplyView)
router.register('PersonApi', PersonApi)
router.register('apiinfo', UserGetInfo)
router.register('all_info', UserGetAllInfo)
# router.register('user_disbale', UserDisbale)
router.register('PersonOthers', PersonOthers)
router.register('UserMessages', UserMessages, base_name='UserMessages')
router.register('article', ArticleCreated)
router.register('courseList', CoursesList)
router.register('mecourseList', MeCoursesList)
router.register('course', CourseCreatedList)
router.register('Addtutorial', CourseListCreated)
router.register('BannerList', BannerList)
router.register('EmailsList', EmailsList)
router.register('LinkList', LinkList)
router.register('forum/category', Forum_plateView)
router.register('forum', ForumView)
router.register('CommentView', CommentView)
router.register('Parent_CommentView', Parent_CommentView)
router.register('get-list',QQList)
router.register('seo-list',SeoList,basename='seo-list')
router.register('UserFollows',UserFollows)
router.register('AppMessage',AppMessage)
router.register('UserFollowOther',UserFollowOther)
router.register('ForumListView',ForumListView)

urlpatterns = [

    #path('admins/', admin.site.urls),
    path('admin/', TemplateView.as_view(template_name='admin/index.html')),
   # path('404/', TemplateView.as_view(template_name='500.html')),
    # path('',test), # 这是生成验证码的图片
    url(r'^captcha/', include('captcha.urls')),
    path('refresh/', captcha_refresh),  # 这是生成验证码的图片
    path('yan/', yan),  # 这是生成验证码的图片
    # path('', Home, name='home'),
    path('', views.Home, name='home'),

    path('webapp/', TemplateView.as_view(template_name='webapp/index.html')),
    path('login/', login_view, name='index'),
    path('info/', get_message, name='info'),
    path('person/', include('apps.user.urls')),
    path('logou/', logout_view, name='logou'),
    path('register/', Register.as_view(), name='register'),
    path('article/', include('apps.article.urls')),
    path('course/', include('apps.course.urls')),
    path('support/', include('apps.support.urls')),
    path('forum/', include('apps.forum.urls')),
    path('ads.txt/',TemplateView.as_view(template_name='ads.txt')),
    path('root.txt/', TemplateView.as_view(template_name='root.txt')),
    path('jd_root.txt/', TemplateView.as_view(template_name='jd_root.txt')),
    path('gome_20943.txt/', TemplateView.as_view(template_name='gome_20943.txt')),
    #url(r'^activate/(?P<token>\w+.[-_\w]*\w+.[-_\w]*\w+)/$', active_user, name='active_user'),
    path('activate/<str:token>', active_user, name='active_user'),
    url(r'^search/', include('haystack.urls'), name='haystack_search'),

    re_path(r'^upload/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path("api-docs/", include_docs_urls("API文档")),
    re_path(r'api/login/$', obtain_jwt_token),  # jwt认证
    re_path(r'^api-token-refresh/', refresh_jwt_token),#jwt刷新
    url('auth-qq', to_login, name='qq-login'),
    url('qq', qq, name='qq'),
    url('callbackget', getClback, name='callbackget'),
    url('getClbackQQ', getClbackQQ, name='getClbackQQ'),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT})  # 配置文件上传html显示
]

#全局404
handler404='apps.user.views.page_not_found'
handler500='apps.user.views.page_error'

apps/article/models.py
import uuid
from datetime import datetime


from django.db import models

from apps.user.models import User
# Create your models here.


class Category_Article(models.Model):
    """
    分类
    """
    name = models.CharField(max_length=100)
    order = models.IntegerField(default=0,verbose_name='排序')
    add_time = models.DateTimeField(default=datetime.now)
    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name


class Article(models.Model):
    """文章"""
    id = models.UUIDField(default=uuid.uuid4,primary_key=True)
    authors = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='用户')
    category = models.ForeignKey(Category_Article,on_delete=models.CASCADE,verbose_name='分类')
    title = models.CharField(max_length=100)
    keywords = models.CharField(max_length=200,blank=True,null=True)
    desc = models.CharField(max_length=256,blank=True,null=True)
    list_pic = models.ImageField(upload_to='article/%Y%m%d',blank=True,null=True)
    content = models.TextField()
    click_nums = models.IntegerField(default=0,verbose_name='阅读数量')
    is_show = models.BooleanField(default=True,verbose_name='是否删除')
    add_time = models.DateTimeField(auto_now_add=True)

    def get_number(self):
        n= self.article_comment_set.all()
        num = self.article_comment_set.count()
        for i in n:
            num+=i.articlecommentreply_set.count()
        return num

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ('-add_time',)


class Recommend(models.Model):
    recommends = models.ForeignKey(Article,on_delete=models.CASCADE,null=True,)
    is_recommend = models.BooleanField(default=False, verbose_name='是否推荐')
    add_time = models.DateTimeField(auto_now_add=True)
    class Meta:
        verbose_name = '文章推荐'
        verbose_name_plural = verbose_name
        ordering = ('-add_time',)


class Article_Comment(models.Model):
    """"评论"""
    user = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='用户')
    article =models.ForeignKey(Article,verbose_name='文章',on_delete=models.CASCADE)
    comments = models.TextField(verbose_name='评论')
    address = models.CharField(max_length=50,verbose_name='地址',blank=True,null=True)
    url = models.CharField(max_length=60, blank=True, null=True, default='')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    def __str__(self):
        return self.article.title

    class Meta:
        verbose_name ='文章评论'
        verbose_name_plural=verbose_name
        ordering = ('-add_time',)



class ArticleCommentReply(models.Model):
    """评论回复"""
    user = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='当前用户',related_name='form_uid')
    to_uids = models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='目标用户',related_name='to_uids',default='')
    comments = models.TextField(verbose_name='回复内容')
    url = models.CharField(max_length=60,blank=True,null=True,default='')
    aomments_id = models.ForeignKey(Article_Comment,on_delete=models.CASCADE,verbose_name='回复id')
    address = models.CharField(max_length=50, verbose_name='地址',blank=True,null=True)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')


class Headlines(models.Model):
    """头条"""
    id = models.UUIDField(default=uuid.uuid4,primary_key=True)
    title = models.CharField(max_length=200,verbose_name='标题')
    category = models.CharField(max_length=20,verbose_name='分类')
    conent = models.TextField(verbose_name='内容',default='')
    author_name = models.CharField(max_length=100,verbose_name='来源')
    url = models.URLField(verbose_name='地址')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        ordering = ('-add_time',)

apps/support/models.py
from django.db import models

# Create your models here.


class Banners(models.Model):
    """
    广告
    """
    title = models.CharField(max_length=100,blank=True,null=True)
    image = models.ImageField(upload_to='support/%Y%m%d',blank=True,null=True)
    url = models.URLField(blank=True,null=True)
    add_time = models.DateTimeField(auto_now_add=True)


class Emails(models.Model):
    """联系方式"""
    qq = models.CharField(max_length=11,blank=True,null=True)
    iphone = models.CharField(max_length=11,blank=True,null=True)
    email = models.EmailField(blank=True,null=True)
    add_time = models.DateTimeField(auto_now_add=True)


class link(models.Model):
    """友情链接"""
    title =  models.CharField(max_length=100)
    url = models.URLField()
    add_time = models.DateTimeField(auto_now_add=True)


class QQ(models.Model):
    """交流群"""
    title =  models.CharField(max_length=100)
    qq = models.IntegerField()
    is_active = models.BooleanField(default=False)


class Seo(models.Model):
    """SEO"""
    name = models.CharField(max_length=100,default='')
    title = models.CharField(max_length=150)
    author = models.CharField(max_length=20)
    desc = models.TextField()
    keywords = models.TextField()

apps/article/forms.py
#!/usr/bin/python  
# -*- coding:utf-8 -*-  
from django import forms

from apps.article.models import Article


class Article_form(forms.ModelForm):
    category = forms.IntegerField(required=True)
    desc = forms.CharField(required=False,max_length=256,error_messages={"max_length":'字段不能超过256'})
    keywords = forms.CharField(required=False,max_length=200,error_messages={"max_length":'字段不能超过200'})
    title = forms.CharField(required=True,max_length=100,error_messages={"max_length":'字段不能超过100'})

    class Meta:
        model = Article
        fields = ['authors','content']

apps/forum/forms.py
#!/usr/bin/python  
# -*- coding:utf-8 -*-  
from django import forms

from apps.forum.models import Forum, Parent_Comment


class Forum_form(forms.ModelForm):
    """
    发布帖子
    """
    category = forms.IntegerField(required=True)
    keywords = forms.CharField(max_length=200,required=False,error_messages={"max_length":'字段不能超过200'})
    title = forms.CharField(required=True, max_length=255, error_messages={"max_length": '字段不能超过255'})

    class Meta:
        model = Forum
        fields = ['authors','content']


class ParentComment(forms.ModelForm):

    class Meta:
        model = Parent_Comment
        fields = ['comments','user','forums','parent_comments','to_Parent_Comments','url']

apps/support/views.py
from django.shortcuts import render

# Create your views here.
from rest_framework import viewsets,mixins
from rest_framework.authentication import SessionAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework_jwt.authentication import JSONWebTokenAuthentication

from apps.article.views import StandardResultsSetPagination
from apps.support.models import Banners, Emails, link, QQ, Seo
from apps.uitls.permissions import IsOwnerOrReadOnly
from apps.support.serializers import BannersSerializer, EmailsSerializer, LinkSerializer, QQSerializer, SEOSerializer


def index(request):
    email = Emails.objects.first()
    return render(request,'pc/support.html',{'email':email})



class BannerList(viewsets.ModelViewSet):
    queryset = Banners.objects.all()
    serializer_class = BannersSerializer
    permission_classes = (IsAuthenticated, IsOwnerOrReadOnly)  # 未登录禁止访问
    authentication_classes = [JSONWebTokenAuthentication]
    pagination_class = StandardResultsSetPagination



class EmailsList(viewsets.ModelViewSet):
    queryset = Emails.objects.all()
    serializer_class = EmailsSerializer
    permission_classes = (IsAuthenticated, IsOwnerOrReadOnly)  # 未登录禁止访问
    authentication_classes = [JSONWebTokenAuthentication]
    pagination_class = StandardResultsSetPagination


class LinkList(viewsets.ModelViewSet):
    queryset = link.objects.all()
    serializer_class = LinkSerializer
    permission_classes = (IsAuthenticated, IsOwnerOrReadOnly)  # 未登录禁止访问
    authentication_classes = [JSONWebTokenAuthentication]
    pagination_class = StandardResultsSetPagination


class QQList(viewsets.ModelViewSet):
    queryset = QQ.objects.all()
    serializer_class = QQSerializer
    permission_classes = (IsAuthenticated, IsOwnerOrReadOnly)  # 未登录禁止访问
    authentication_classes = [JSONWebTokenAuthentication]


class SeoList(mixins.CreateModelMixin,mixins.DestroyModelMixin,mixins.ListModelMixin,mixins.UpdateModelMixin,mixins.RetrieveModelMixin,viewsets.GenericViewSet):
    queryset = Seo.objects.all()
    serializer_class = SEOSerializer
    # permission_classes = (IsAuthenticated, IsOwnerOrReadOnly)  # 未登录禁止访问
    # authentication_classes = [SessionAuthentication, JSONWebTokenAuthentication]

templates/pc/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge,chrome=1">
    <meta name="keywords" content="{% block keywords %}
    {% endblock %}">
    <meta name="description" content="{% block desc %}
    {% endblock %}">
    <meta name="author" content="{% block authors %}
    {% endblock %}">
    <title>{% block title %}{% endblock %}</title>
    <link rel="shortcut icon" href="{% static 'img/logo.png' %}">
    <link rel="stylesheet" href="{% static 'css/public.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <style>
        #cnzz_stat_icon_1277918196{
        position: absolute;
        bottom: 15px;
        z-index: 1;
            margin-bottom: 0;
        }
    </style>
    {% block css %}{% endblock %}
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/jquery.cookie.min.js' %}"></script>
    <script src="{% static 'js/public.js' %}"></script>
    <script src="{% static 'js/xss.js' %}"></script>
    <script src="{% static 'js/promise.min.js' %}"></script>
    <script src="{% static 'js/sweetalert.min.js' %}"></script>
    {% block link_js %}
    {% endblock %}
</head>
<body>
<header>
    <div class="main clearfix">
        <a class="fl logo" href="{% url 'home' %}" style="height:45px;background: url({% static 'img/logo.png' %})no-repeat;width: 120px;background-size: 120px 45px;
    margin-top: 7px;">
{#            <img style="width: 40px;margin-top: 20px;" src="{% static 'img/logo.png' %}" alt="">#}
        </a>
        <nav class="fl">
            <ul class="clearfix headers_nav">
{#                <li class="fl"><a class="{% if request.path == '/' %}#}
{#                active#}
{#                {% endif %}" href="{% url 'home' %}">首页</a></li>#}
                <li class="fl"><a class=" {% if request.path|slice:'9' == '/article/' %}
                active
                {% endif %}"href="{% url 'article:index' %}">首页</a></li>

                <li class="fl"><a class=" {% if request.path|slice:'8' == '/course/' %}
                active
                {% endif %} "href="{% url 'course:index' %}">教程</a></li>
             <li class="fl"><a class=" {% if request.path|slice:'7' == '/forum/' %}
                active
                {% endif %}" href="{% url 'forum:forum' %}">社区论坛</a></li>
{#                <li class="fl"><a class=" {% if request.path|slice:'9' == '/support/' %}#}
{#                active#}
{#                {% endif %}" href="{% url 'support:support' %}">支持与赞助</a></li>#}
            </ul>
        </nav>
        <div class="fr user">
            <ul class="clearfix"style="display:flex;display: -webkit-flex;">
            <li>
                <form role="search" method="get" id="searchform" action="{% url 'haystack_search' %}">
                  <input type="text" name="q" placeholder="搜索" required class="form_control">
{#                  <button type="submit">#}
                      <button type="submit" class="form_search"></button>
{#                  </button>#}
                </form>
            </li>
                <li class="fl style" style="background: url({% static 'img/public.png' %})no-repeat 0 50%;"><a href="{% url 'article:created' %}">写文章</a></li>
{#                <li class="fl style" style="background: url({% static 'img/phone.png' %})no-repeat 0 50%;"><a href="">手机阅读</a></li>#}
                {% if request.user.is_authenticated %}
                    <li class="fl avatar">
                        <a class="img_cover" style="background: url({% if request.user.user_imag %}
                            {{ MEDIA_URL }}{{ request.user.user_imag  }}
                            {% elif request.user.user_image %}
                            {{ request.user.user_image }}
                            {% else %}
                            {% static 'img/pc-icon.png' %}
                        {% endif %})no-repeat;">
                        <b id="yuan" style="width: 10px;height: 10px;
                        position: absolute;
                        display: none;
                        right: 0;
                        background: red;-webkit-border-radius: 50%;-moz-border-radius: 50%;border-radius: 50%;"></b>
                        </a>
                        <ul class="meau meau_hide">
                            <li><a href="{% url 'user:person' %}">个人中心</a></li>
                         <li><a href="{% url 'user:message' %}">消息<span class="badge" style="display: none;"></span></a></li>
                            {% if user.is_staff  %}
                                <li><a href="/admin">系统管理</a></li>
                            {% endif %}
                            <li><a href="{% url 'logou' %}">退出</a></li>
                        </ul>
                    </li>
                    {% else %}
                    <li class="fl"><a href="/login">登录 </a> | <a href="{% url 'register' %}"> 注册</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</header>
{% block content %}

{% endblock %}

<footer class="footer">
    <p class="main">Powered by
        <a>爱上她的歌</a>
        <a href="http://www.miitbeian.gov.cn" target="_blank">蜀ICP备18023241号-1</a>
    </p>
</footer>
 <a href="javascript:;" id="toTop" class=" fa fa-chevron-up"></a>
<script>
var os = function() {
    var ua = navigator.userAgent,
        isWindowsPhone = /(?:Windows Phone)/.test(ua),
        isSymbian = /(?:SymbianOS)/.test(ua) || isWindowsPhone,
        isAndroid = /(?:Android)/.test(ua),
        isFireFox = /(?:Firefox)/.test(ua),
        isChrome = /(?:Chrome|CriOS)/.test(ua),
        isTablet = /(?:iPad|PlayBook)/.test(ua) || (isAndroid && !/(?:Mobile)/.test(ua)) || (isFireFox && /(?:Tablet)/.test(ua)),
        isPhone = /(?:iPhone)/.test(ua) && !isTablet,
        isPc = !isPhone && !isAndroid && !isSymbian;
    return {
        isTablet: isTablet,
        isPhone: isPhone,
        isAndroid: isAndroid,
        isPc: isPc
    };
}();
   if(os.isAndroid || os.isPhone) {
   window.location.href=window.location.hash+'/webapp/#'
} else if(os.isTablet) {
    window.location.href=window.location.hash+'/webapp/#'
}
    $(function(){
        {% if request.user.is_authenticated %}

        $.ajax({
            url:'/info/',
            type:'get',
            success:function (data) {
                $('span.badge').text(data.count)
                if(data.count>0){
                    $("#yuan").show()
                     $('span.badge').show()
                }
            }
        })
        {% endif %}

        $('.avatar').click(function(event){
            event.stopPropagation();
            $('.meau').fadeIn()
        })
        $(document).click(function(){
            $(".meau").fadeOut();
            });
        $(window).scroll(function(){
                if ($(window).scrollTop()>100){
                    $("#toTop").fadeIn(1500);
                }
                else
                {
                    $("#toTop").fadeOut(1000);
                }
        });
            //当点击跳转链接后，回到页面顶部位置
            $("#toTop").click(function(){
                $('body,html').animate({scrollTop:0},500);
                return false;
            });
        //底部栏位置始终在最底部
        //console.log(window.screen.availHeight)
        $("body").css({
            "min-height": $(window).height()
        })
    })
</script>
{% block js %}
{% endblock %}
</body>
</html>

templates/pc/forum_category.html
{% extends 'pc/forum.html' %}
{% load static %}
{% block title %}
论坛社区-{{type.name }}
{% endblock %}
{% block keywords %}
论坛社区|冯金琪,问题求助、代码、技术分享、综合讨论、求职招聘，js,js学习,Vue,React,前端学习,后台学习,服务器学习教程,数据库,mysql等学习,Java学习，ssh框架,PHP学习等，技术交流社区博客
{% endblock %}
{% block desc %}
论坛社区|冯金琪-技术交流社区博客,欢迎大家加入本站，本站是纯IT技术交流学术网站,在这里大家可以技术交流学习,发布文章,发布教程，一起学习成长，问题求助、代码、技术分享、综合讨论，在这里你可以进行技术分享、帮助别人解决问题。求职招聘，网站反馈等
{% endblock %}
{% block childer %}
 <div style="background: #fff;">
            <div class="f-name">
                <span class="active">最新帖子>>{{type.name  }}</span>
            </div>

            <ul class="list">
                {% for foo in people.object_list %}
                    <li class="clearfix">
                        <img src="{% if foo.authors.user_imag %}
                    {{ MEDIA_URL }}{{ foo.authors.user_imag }}
                    {% elif foo.authors.user_image %}
                    {{ foo.authors.user_image }}
                    {% else %}
                    {% static 'img/pc-icon.png' %}
                    {% endif %}" class="user fl" title="{{ foo.authors.username }}"width="40px">
                    <div class="list-text fl">
                        <p class="forun-title"><a href="{% url 'forum:detail' foo.id %}">{{ foo.title }}</a></p>
                        <p class="forun-info">来自于 {{ foo.category.name }}  {{ foo.add_time }} </p>
                    </div>
                    <div class="fr flex forun-num">
                        <div>评论{{ foo.get_number }}</div>
                        <div>浏览{{ foo.click_nums }}</div>
                    </div>
                    </li>
                    {% empty %}
                     <li style="margin: 10px 0">...暂无帖子</li>
                {% endfor %}
            </ul>

            {% if people.object_list.count >= 1 %}
        <div class="pageturn"style="padding: 15px">
           <ul class="pagination">
{#               <li><a href="/index">首页</a></li>#}
               {% if people.has_previous %}
                   <li class="long"><a href="?{{ people.previous_page_number.querystring }}" class="prev">上一页</a></li>
               {% else %}
                   <li class="long"><span class="disabled prev btn"disabled="">上一页</span></li>
               {% endif %}
               {% for page in people.pages %}
                   {% if page %}
                       {% ifequal page people.number %}
                           <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                       {% else %}
                           <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                       {% endifequal %}
                   {% else %}
                       <li><span class="disabled  btn" disabled="">...</span></li>
                   {% endif %}
               {% endfor %}
               {% if people.has_next %}
                   <li class="long"><a href="?{{ people.next_page_number.querystring }}" class="next"> 下一页</a></li>
               {% else %}
                   <li class="long"><span class="disabled next btn"disabled=""> 下一页</span></li>
               {% endif %}
{#               <li><a href="?page={{ article.paginator.num_pages }}">尾页</a></li>#}
               <li class="hrefto">跳转到<input type="text"class="form-control" name="page"></li>
           </ul>

            当前{{ people.number }}/总共{{ people.paginator.num_pages }}页
       </div>
    {% endif %}

        </div>
{% endblock %}

templates/pc/message.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
     <link rel="shortcut icon" href="{% static 'img/logo.png' %}">
</head>
<body>
<p>{{ message|safe }}</p>
</body>
</html>